### ISSUE TITLE
Confusion matrix plotted incorrectly

### ISSUE THREAD

**Issue by willw1** [eminSerin/NBS-Predict#10]
The elements on the leading diagonal of confmat need to be switched for the confusion matrix to plot correctly. 

`confmat = fliplr(fliplr(confmat)');`

in function `confMatPush_Callback()` works as a hack.

**Comment by eminSerin** [comment]
Hi, 

Thank you so much for your interest in the toolbox and for informing me! I fixed the issue in the dev branch (see 6a2115d). The master branch will be updated along with additional features and fixes in the following days. 

Best,
Emin
