### ISSUE TITLE
FC Matrix

### ISSUE THREAD

**Issue by M31glx** [eminSerin/NBS-Predict#2]
Hi
![nbs-predict](https://user-images.githubusercontent.com/42111096/136129168-0a55e8cf-67da-4be2-a519-6eebdc9553a3.png)
 Emin, I was trying to test your software but when I tried to import the FC matrix (333x333x57), it doesn't allow me to select it from the selection bar! (no option for selecting CSV or mat file). Is this normal?

**Comment by eminSerin** [comment]
I will close this issue unless you have further questions :)
