### ISSUE TITLE
Estimate weights for confound regression in one group 

### ISSUE THREAD

**Issue by Giuseppe1988** [eminSerin/NBS-Predict#21]
Hi,

I am using NBS-predict to predict disease status (patients vs healthy controls) based on functional connectome data, with age and sex as nuisance variables.
Regarding confound regression, given the strong correlation between age and disease duration, I was afraid that estimating confound weights on the whole population might lead to regressing-out some disease-related effects from patients' data. Is this concern justified?
 
Would it be possible to estimate the weights only in the HCs and then regress-out the effect of physiological aging from all subjects?

Thank you in advance for your help and for this great resource!

Best,
Giuseppe

**Comment by eminSerin** [comment]
Hi Giuseppe, 

Thank you so much for your interest in our toolbox and for reaching out. Yes, your concern is totally sensible. That is actually one drawback of confound regression, as it might also remove some signals strongly associated with confound. What you asked for sounds like a great feature, but unfortunately, the toolbox does not allow that in the current version.
