### ISSUE TITLE
CV length error

### ISSUE THREAD

**Issue by ajdneuro** [eminSerin/NBS-Predict#23]
Hello,
Thank you for this wonderful resource.

I am running into this error: Error using tabular/length
Undefined function 'LENGTH' for input arguments of type 'table'.  Use the height, width, or size
functions instead.

Error in gen_cvpartition (line 20)
leny = length(y);

I was wondering where I should start for troubleshooting?

Thanks,
Alex

**Comment by eminSerin** [comment]
Dear Alex,

Thank you for your interest in our toolbox, NBS-Predict. I apologize for the delay in responding to your issue on GitHub, as I did not receive a notification for it.

In regards to your issue, you provided a design matrix in a table structure, whereas our toolbox requires it to be in a matrix structure. You can refer to our [sample dataset](https://www.nitrc.org/docman/index.php?group_id=1517&selected_doc_group_id=6429&language_id=1#folder) to understand the correct input format.

If you still have any issues, please don't hesitate to contact us for further assistance.
