### ISSUE TITLE
No graph produced when contrast [1 1]

### ISSUE THREAD

**Issue by ramBrain** [eminSerin/NBS-Predict#26]
Dear Emin,

If I try and run the toolbox by setting the contrast as [1 1] (which should be an F-test, or ANOVA, right?) I get some accuracy score but no meaningful graph, just a matrix where all connections are weighted 1. Is this an expected behavior?

Thank you,
Ramtin

**Comment by eminSerin** [comment]
Hi Ramtin,

Thank you for your interest in our toolbox. To use a network-based F-test as a feature selection method for regression problems, you will need to set the contrast as [0 1]. Please try running your analysis with this contrast and let me know how it goes.

Good luck with your analyses!
Emin

**Comment by ramBrain** [comment]
Hi Emin,

Thank you for your answer.

I am trying to solve a classification problem, with two groups. I would need to run a two-tailed t-test (or an ANOVA). With the classic NBS the contrast would be [1 1] (F-test), is it not the same here?

Many thanks,
Ramtin
