### ISSUE TITLE
Interpretation of the results generated by NBS-predict

### ISSUE THREAD

**Issue by DrHuaYu** [eminSerin/NBS-Predict#27]
Dear Dr. Serin, 
I am a psychiatrist form China. Recently, I am using functional conenctome to predict HAMD depression scores. I am seting the parameter to 10 fold, 10-repetad times, and the p value to 0.0005. The results showed the HAMD scores can be predicted with  µScore: 0.155, σScore: 0.012 by using SVM method and with µScore: 0.147, σScore: 0.017 by using linear regression. However, I am confused about the results, cause when I choose the SVM regression and correlation method, I found the R squared value is 0.003, and r corelation is 0.155 for SVM method. While, when I choose the linear regression and correlation method, I found the R squared value is -0.122, and r correlation is 0.147 for linear correlation method. The brain regions presentd for the two different method are also quite different. Can you tell me which method shoul I choose, or I can choose randomly?

Second, the R squred for linear regression is -0.122 is unbelieveble. What's more, I can't tell it is a positive prediction or negative prediction of the HAMD scores. Can you tell me how to see if it is a positive corelation or negative corelation?

Looking forward for your reply. All the best,
Hua

**Comment by eminSerin** [comment]
Dear Hua,

Thank you for reaching out and expressing interest in our toolbox. In order for me to provide more specific advice, could you please provide me with more details about your data, such as the size of the input matrix and the number of subjects? 

In general, it is not uncommon to see significant differences between R2 and correlation values, which may indicate that the prediction performance is not reliable or significant. Additionally, it is expected that you would observe similar brain regions being implicated by both machine learning methods. If this is not the case, it may suggest that your sample size is insufficient for the prediction task.

I hope this information is helpful, and I look forward to hearing more about your analyses.

Good luck!
Emin
