### ISSUE TITLE
Unrecognized function or variable 'adjMat'.

### ISSUE THREAD

**Issue by vdkreft** [eminSerin/NBS-Predict#33]
Hello! 

I have ran into a new error with your toolbox. It seems that the code has run into an error when reaching the visualization step. 
Here was the error message:

> Unrecognized function or variable 'adjMat'.

My parameters are slightly different than my last issue so here they are again:

Contrast: [1,-1,0,0]
ML Model: Auto
K-Fold: 10
Repeat CV: 10
P-value: 0.01
Seed: 42
CPU Cores: 10
Method: Grid Search

Please let me know if this is trouble on my end!

**Comment by eminSerin** [comment]
Hi again, 

If your analyses are completed with errors, you should be fine. You might be using the pre-release version. Please download the following version: https://github.com/eminSerin/NBS-Predict/releases/tag/v1.0.0-beta.10 , and let me know how it goes.

**Comment by vdkreft** [comment]
Hello,

It seems like the version you sent me might be the same as the one I was currently using. Here is the full error message which may give you some more insight into the issue:

`Results are being saved...`
`Warning: Variable 'NBSPredict' was not saved. For variables larger than 2GB use MAT-file version 7.3 or later.` 
`In run_NBSPredict (line 180)`
`In run_NBSPredictGUI>runNBSPredict_Callback (line 736)`
`In gui_mainfcn (line 95)`
`In run_NBSPredictGUI (line 42)`
`In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)run_NBSPredictGUI('runNBSPredict_Callback',hObject,eventdata,guidata(hObject))`

`Thank you for using NBS-Predict!
Please contact to emin.serin@charite.de for any questions, suggestions or bug reports.`

`Welcome to NBS-Predict GUI!
NBS-Predict GUI is graphical user interface to deliver user input and run NBS-Predict.
Please check MANUAL by clicking Help button!`

`Unrecognized function or variable 'adjMat'.`

`Error in view_NBSPredict>plotUpdatedData (line 586)
        update_NBSPredictFigure(adjMat, handles.plotData.brainRegions.labels,...`

`Error in view_NBSPredict>view_NBSPredict_OpeningFcn (line 144)
handles = plotUpdatedData(handles);`

`Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});`

`Error in view_NBSPredict (line 42)
    gui_mainfcn(gui_State, varargin{:});`

`Error in run_NBSPredict (line 185)
    view_NBSPredict(NBSPredict);`

`Error in run_NBSPredictGUI>runNBSPredict_Callback (line 736)
run_NBSPredict(handles.NBSPredict);`

`Error in gui_mainfcn (line 95)
        feval(varargin{:});`

`Error in run_NBSPredictGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});`

`Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)run_NBSPredictGUI('runNBSPredict_Callback',hObject,eventdata,guidata(hObject))`
 
`Error while evaluating UIControl Callback.`

Please let me know if you figure anything out!

**Comment by eminSerin** [comment]
Thank you for bringing this to my attention. It appears there is a bug in the code that I will work on fixing by tomorrow. I apologize for any inconvenience this may have caused. In the meantime, you can utilize the previous version of the toolbox, which can be found at https://github.com/eminSerin/NBS-Predict/releases/tag/v1.0.0-beta.9 and does not have this particular bug. It is worth noting that the differences between the two versions are minimal and should not impact your analyses.

**Comment by vdkreft** [comment]
Thank you so much! Keep me posted about the debugging.

**Comment by vdkreft** [comment]
Hello!
Seems like the hotfix made it work! Thank you again and I think this can be closed!

**Comment by eminSerin** [comment]
Great! Good luck with your analyses!
