### ISSUE TITLE
Inconsistent Learning Performance with Default Tutorial Data and Parameters

### ISSUE THREAD

**Issue by jurriolayak** [eminSerin/NBS-Predict#37]
### **Issue Description**:

We are encountering an issue where the NBS-Predict algorithm is not learning effectively when using the default tutorial data and parameters. The output consistently shows average AUC scores around 0.5, which suggests that the model is not performing better than random chance.

### **Environment**:
* NBS-Predict Version: 1.0.0-beta.10 
* MATLAB Version: R2021b
* Operating System: SUSE 15.3

### **Steps to Reproduce our issue**:
* Cloned the NBS-Predict repository from GitHub.
* Used the sample data provided in the NITRC link in the documentation.
* Followed the standard procedure as per the Tutorial_HCP.pdf file.
  * Ran the analysis with the following initial parameters:
  * Searching Algorithm: bayesOpt
  * METRIC: auc
  * Number of Folds: 10
  * Number of Repetitions: 10

![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/290cbc67-95ac-4244-95c6-69136867d138)

Results: The algorithm consistently returned AUC scores around 0.5. With the default tutorial data and parameters, I expected the algorithm to learn effectively and provide AUC scores significantly different from 0.5, but the following is the MATLAB command window output:

```
ESTIMATOR: LogReg
Searching Algorithm: bayesOpt
METRIC: auc
Number of Folds: 10
Number of Repetitions: 10
-------------
|   Score   |
-------------
|   0.490   |
|   0.496   |
|   0.475   |
|   0.498   |
|   0.507   |
|   0.490   |
|   0.506   |
|   0.507   |
|   0.498   |
|   0.500   |
-------------
10x10 repeated-CV: µScore: 0.497, σScore: 0.010
The elapsed time is 61.308250 seconds.
Permutation testing is running! Permutations: 1000 
```
The confusion matrix also showed that the predictions were not reflect correct true positive and true negative values
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/527f0c4b-ada0-40eb-b490-8b913c4066d3)
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/486ac5cb-17d2-46fe-80b5-bd3e901e3993)

To note: We have not modified the default settings or data in any significant way. The issue persists even after repeating the analysis on different computers with different OS, Matlab versions with different parameters. 

### **Given our results we have the following questions:**
Is there a known issue with the current version of NBS-Predict that might be causing this behaviour? 
Could there be an issue with the data, the choice of model/hyperparameters, or a potential bug in the software?
Any assistance or guidance you could provide would be greatly appreciated.

Best regards, 
Javier

**Comment by eminSerin** [comment]
Hi Javier, 

Thanks a lot for the very detailed issue. That's because you might use the wrong dataset for this classification analysis, or your contrast vector is incorrect. Can you provide more information about which dataset you used and the contrast vector?  Cheers!

**Comment by jurriolayak** [comment]
Hi Emin, 

Thank you very much for your prompt reply. We have tried to troubleshoot the issue with multiple users. We downloaded the dataset from the NITRC link on the GitHub page following this link: https://www.nitrc.org/docman/view.php/1517/179438/

The contrast used is: [-1,1]. Below is the image of the setup window
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/9b62cb39-7c2c-43c8-8113-4ed641f9e860)

Also the contrast vector seems correct in the design.mat file as seen in the picture below
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/4c9c7d19-02b8-42db-8f65-92c33f414b9c)

Please feel free to let us know if there is something that we missed, 
Best, 

Javier

**Comment by eminSerin** [comment]
Hi Javier, 

Thanks for the information. Now I see the problem. The real contrast is Group 1 > Group 2, meaning the contrast vector must be [1, -1] instead. Since I did not implement any effect of interest in Group 2, it's expected to see prediction at the level of chance. Please change the contrast vector and re-run it again. You will notice a prediction performance of ~ 0.74.

**Comment by jurriolayak** [comment]
Hi Emin, 
Thank you very much again for your comments. We followed them using the contrast [1,-1] as suggested (please see images below). The results differed from the previous contrast, but it seems that it does not match the same results as in the documentation. The confusion matrix also hits that there is something that we are doing that is not correct, but cannot figure it out the problem. I have attached the images below. We will greatly appreciate your help. Please don't hesitate to ask for additional information if you require to replicate this issue. 

**Setup**
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/940d44d5-adb3-414b-b411-26097921b740)

**Learning stage**
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/ca80d1d0-af52-46de-a844-f0d1a84a48c0)

**Outcome**
![image](https://github.com/eminSerin/NBS-Predict/assets/148017632/e13671c3-b0c2-4a5e-bd1e-e5c39515a175)


Thank you, 

Javier

**Comment by eminSerin** [comment]
Hi Javier,

MinMaxScaler is the primary reason for the inconsistent outcomes you are experiencing. Scaling may not always improve the results, and in some cases, it may even worsen them. Therefore, I strongly advise you to either skip the scaling altogether or explore alternative classifiers such as LDA. Moreover, Bayesian Optimization is not beneficial in this situation. Therefore, I suggest you use the Grid Method instead.

Good luck! 

Best of luck!
