### ISSUE TITLE
Regression analysis

### ISSUE THREAD

**Issue by kbatista-gr** [eminSerin/NBS-Predict#41]
Is it possible to perform regression analysis between two groups, similar to NBS? For example:
1st column: intercept
2nd column: interaction between diagnosis and behavioural measure
3rd column: behavioural measure
4th column: patient or control

**Comment by kbatista-gr** [comment]
Thank you very much for your quick response and congratulations!, NBS-Predict is a great tool.

Sorry, I'm still confuse.

I have two groups (30 subjects in each one) and one behavioural measure. The question is the association group*behavioural interaction
1st column: columns of ones (n = 60)
2nd column: behavioural metric
3rd column: patient or control (30 ones, 30 zeros)
Contrast: [0, 1, 0]
But in this case, what I understand is that it would be evaluating if connectivity predicts the behavioural metric taking into account the two groups, but it would not be evaluating the interaction.
Is it possible to evaluate if changes in connectivity are associated with the behavioural metric?

**Comment by eminSerin** [comment]
Hi, 

I'm sorry for not getting back to you sooner. As NBS-Predict runs machine learning algorithms, it does not handle interaction between target variables. With your contrast vector, what it does instead is to remove the group effect from your input (connectivity matrices) and predict the "behavioral metric" using corrected input. 

> Is it possible to evaluate if changes in connectivity are associated with the behavioral metric?

 – Unfortunately, not.

**Comment by kbatista-gr** [comment]
Thank you very much for your clarification. I understand now.
