### ISSUE TITLE
Inquire about global signal processing during the use of NBS-Predict

### ISSUE THREAD

**Issue by Wut99** [eminSerin/NBS-Predict#44]
Dear Prof. Serin
I am sorry to disturb you, but I have a question while reading your article “NBS-Predict: A prediction-based extension of the network-based statistic”. We would like to know if the FC matrix used in NBS-Predict does not need to undergo a global signal regression? Although it is still a controversial issue whether the FMRI signals require global signal regression, it is still not clear to us why the FC matrix used for NBS-Predict does not need to be regressed. Finally, thank you very much for developing and sharing this toolkit.
Yours sincerely,
WuTONG

**Comment by eminSerin** [comment]
Dear Wutong,

Thank you very much for your interest in our toolbox and for reaching out. We do not make any assumptions regarding global signal regression, as this is beyond the scope of our toolbox. As you mentioned, this is a contentious issue, and we recommend selecting the most widely accepted and plausible approach for your preprocessing. Unfortunately, I am not currently up to date on the latest discussions surrounding this topic, so please correct me if my understanding is incorrect. As I recall, not regressing out the global signal has been the prevailing approach.

Good luck with your analyses, and please do not hesitate to ask any further questions.
